### ISSUE TITLE
Any installing suggestions about  Ghidra on MacOS?

### ISSUE THREAD

**Issue by pharazone** [d3v1l401/FindCrypt-Ghidra#2]
Hello, I use MacOS, so I wonder if I could install this tool on my Mac for Ghidra?

Thank you.

**Comment by d3v1l401** [comment]
Yes, you should be able to run it as well on Mac osx.
I am not familiar with Apple's OS but since it's very much similar to Unix systems, you should be able to install similarly to Linux'a guidelines I wrote.

Please let me know if you find difficulties.

**Comment by d3v1l401** [comment]
I'll close this, if you'll have problems you can open another Issue.

**Comment by duraki** [comment]
Actually, @pharazone seems to be right. Might relate to #3.

**Comment by d3v1l401** [comment]
> Actually, @pharazone seems to be right. Might relate to #3.

Please update the script to the latest version as I described in #3
